name: Hello World Action

on:
  push:
    branches: [ main ]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:

    - name: Install dtt
      uses: philiprbrenan/AppaApps_dtt@dtt
          
